### ISSUE TITLE
define SND_AUDIOCODEC_DSD and SND_AUDIOCODEC_APTX

### ISSUE THREAD

**Issue by pavlaras** [CypherOS/kernel_oneplus_msm8996#1]
1) https://gerrit.omnirom.org/#/c/25631/2/include/uapi/sound/compress_params.h

2) https://gerrit.omnirom.org/#/c/25634/1/include/uapi/sound/compress_params.h

**Comment by Sirhc95** [comment]
Thanks

**Comment by Sirhc95** [comment]
Fixed in our rebase: https://github.com/CypherOS/kernel_oneplus_msm8996
